version: '3.7'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/food_truck_db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
